services:
  - type: web
    name: convertflix-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://flixconvert_user:flixconvert123@cluster0.bscos9h.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: convertflix_super_secret_key_2024_taliyo_technologies
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: harshbudhauliya882@gmail.com
      - key: EMAIL_PASS
        sync: false
      - key: ADMIN_EMAIL
        value: harshbudhauliya882@gmail.com
      - key: ADMIN_PASSWORD
        value: admin123456
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
